//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParaGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Para
    {
        public string ParaId { get; set; }
        public string ParaText { get; set; }
    
        public virtual ParaLeft ParaLeft { get; set; }
        public virtual ParaRight ParaRight { get; set; }
    }
}
