//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParaGenerator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ParaDBEntities : DbContext
    {
        public ParaDBEntities()
            : base("name=ParaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Para> Paras { get; set; }
        public virtual DbSet<ParaLeft> ParaLefts { get; set; }
        public virtual DbSet<ParaRight> ParaRights { get; set; }
    
        public virtual int initialize()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("initialize");
        }
    
        public virtual int move(string paraId, string direction)
        {
            var paraIdParameter = paraId != null ?
                new ObjectParameter("ParaId", paraId) :
                new ObjectParameter("ParaId", typeof(string));
    
            var directionParameter = direction != null ?
                new ObjectParameter("Direction", direction) :
                new ObjectParameter("Direction", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("move", paraIdParameter, directionParameter);
        }
    }
}
